doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        types:
            user_id: App\User\Infrastructure\Doctrine\Type\UserIdType
            money: App\Shared\Infrastructure\Doctrine\Type\MoneyType
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Order:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Order/Infrastructure/Doctrine/Entity'
                prefix: 'App\Order\Infrastructure\Doctrine\Entity'
                alias: App\Order

            App\Product:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Infrastructure/Doctrine/Entity'
                prefix: 'App\Product\Infrastructure\Doctrine\Entity'
                alias: App\Product

            App\Product\Domain:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Product\Domain\Model'
                alias: App\Product\Domain

            App\Shared:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Entity'
                prefix: 'App\Shared\Infrastructure\Doctrine\Entity'
                alias: App\Shared

            App\User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Doctrine/Entity'
                prefix: 'App\User\Infrastructure\Doctrine\Entity'
                alias: App\User

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
