framework:
    messenger:
        default_bus: command.sync.bus
        buses:
            query.bus: ~
            command.sync.bus:
                middleware:
                    - App\Shared\Infrastructure\Bus\Messenger\Middleware\CorrelationIdMiddleware
                    - doctrine_close_connection
                    - doctrine_transaction
            command.async.bus:
                middleware:
                    - App\Shared\Infrastructure\Bus\Messenger\Middleware\CorrelationIdMiddleware
                    - doctrine_close_connection
                    - doctrine_transaction
            event.bus:
                middleware:
                    - App\Shared\Infrastructure\Bus\Messenger\Middleware\CorrelationIdMiddleware
                    - doctrine_transaction
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        transports:
            events:
                dsn: '%env(MESSENGER_RABBITMQ_TRANSPORT_DSN)%'
                options:
                    confirm_timeout: 5
                    connect_timeout: 5
                    read_timeout: 5
                    write_timeout: 5
                    exchange:
                        name: domain_events
                        type: direct
                        default_publish_routing_key: events
                    queues:
                        domain_events:
                            binding_keys: [events]
                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
            sync:
                dsn: 'sync://'
            async:
                dsn: '%env(MESSENGER_RABBITMQ_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: commands
                    queues:
                        commands:
                            binding_keys:
                                - commands
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
            failed:
                dsn: '%env(MESSENGER_DOCTRINE_TRANSPORT_DSN)%'
                options:
                    queue_name: failed
                    auto_setup: false
        failure_transport: failed
        routing:
            App\Shared\Application\Bus\Command\Sync\Command: sync
            App\Shared\Application\Bus\Command\Async\Command: async
