framework:
    workflows:
        order_state:
            type: state_machine
            audit_trail:
                enabled: false
            marking_store:
                type: 'method'
            supports:
                - App\Order\Infrastructure\Doctrine\Entity\Order
            initial_marking: !php/enum App\Order\Domain\Enum\StatusOrder::CREATED->value
            places:
                !php/enum App\Order\Domain\Enum\StatusOrder::CREATED->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::PENDING_PAYMENT->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::PAID->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::PROCESSING->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::READY_FOR_SHIPMENT->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::SHIPPED->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::DELIVERED->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::AWAITING_RECEIPT->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::RETRIEVED->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::CANCELLED->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::RETURN_REQUESTED->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::RETURNED->value: null
                !php/enum App\Order\Domain\Enum\StatusOrder::FAILED->value: null
            transitions:
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::PAY->value:
                    from: !php/enum App\Order\Domain\Enum\StatusOrder::CREATED->value
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::PENDING_PAYMENT->value
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::CONFIRM_PAYMENT->value:
                    from: !php/enum App\Order\Domain\Enum\StatusOrder::PENDING_PAYMENT->value
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::PAID->value
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::PROCESS_ORDER->value:
                    from: !php/enum App\Order\Domain\Enum\StatusOrder::PAID->value
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::PROCESSING->value
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::MARK_READY_FOR_SHIPMENT->value:
                    from: !php/enum App\Order\Domain\Enum\StatusOrder::PROCESSING->value
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::READY_FOR_SHIPMENT->value
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::SHIP->value:
                    from: !php/enum App\Order\Domain\Enum\StatusOrder::READY_FOR_SHIPMENT->value
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::SHIPPED->value
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::DELIVER->value:
                    from: !php/enum App\Order\Domain\Enum\StatusOrder::SHIPPED->value
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::DELIVERED->value
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::CANCEL->value:
                    from: [
                        !php/enum App\Order\Domain\Enum\StatusOrder::CREATED->value,
                           !php/enum App\Order\Domain\Enum\StatusOrder::PENDING_PAYMENT->value,
                           !php/enum App\Order\Domain\Enum\StatusOrder::PAID->value,
                           !php/enum App\Order\Domain\Enum\StatusOrder::PROCESSING->value,
                           !php/enum App\Order\Domain\Enum\StatusOrder::READY_FOR_SHIPMENT->value
                    ]
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::CANCELLED->value
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::REQUEST_RETURN->value:
                    from: !php/enum App\Order\Domain\Enum\StatusOrder::DELIVERED->value
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::AWAITING_RECEIPT->value
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::RETRIEVED->value:
                    from: !php/enum App\Order\Domain\Enum\StatusOrder::AWAITING_RECEIPT->value
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::RETRIEVED->value
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::COMPLETE_RETURN->value:
                    from: !php/enum App\Order\Domain\Enum\StatusOrder::RETURN_REQUESTED->value
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::RETURNED->value
                !php/enum App\Order\Domain\Enum\StatusOrderTransition::FAIL_PAYMENT->value:
                    from: !php/enum App\Order\Domain\Enum\StatusOrder::PENDING_PAYMENT->value
                    to: !php/enum App\Order\Domain\Enum\StatusOrder::FAILED->value

