version: '3.8'

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    volumes:
      - ./etc/docker/sql/images:/sql_images
      - database_storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbname
    ports:
      - "13306:3306"
    networks:
      - app

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    working_dir: /var/www
    restart: always
    volumes:
      - .:/var/www
      - ./etc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app

  php83:
    build:
      context: .
      dockerfile: ./etc/docker/php-fpm/Dockerfile
    container_name: php83
    working_dir: /var/www
    environment:
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_CONFIG: "idekey=PHPSTORM"
    volumes:
      - .:/var/www
      - ./etc/docker/php-fpm/php.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini
      - ./etc/docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "9001:9000"
    depends_on:
      - mariadb
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    volumes:
      - /sessions
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8883:80"
    networks:
      - app

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app

  rabbit:
    image: rabbitmq:3.8.2-management
    container_name: rabbitmq
    ports:
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    volumes:
      - ./etc/docker/volumes/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - app

  mongo:
    image: mongo
    container_name: 'mongodb'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "admin"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - '27017:27017'
    volumes:
      - ./etc/docker/volumes/mongo:/data/db
    networks:
      - app

  mongo-express:
    image: mongo-express
    container_name: 'mongo_express'
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=docker-cluster-app
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.17.25
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    restart: always
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
  database_storage:
