user:
    resource:
        path: ../src/User/UI/Controller/
        namespace: App\User\UI\Controller
    type: attribute

api_login_check:
    path: /api/login_check

api_logout:
    path: /api/logout