api_login_check:
    path: /api/login_check

api_admin_login_check:
    path: /api/admin/login_check

order:
    resource:
        path: ../src/Order/UI/Controller/
        namespace: App\Order\UI\Controller
    type: attribute

product:
    resource:
        path: ../src/Product/UI/Controller/
        namespace: App\Product\UI\Controller
    type: attribute

shared:
    resource:
        path: ../src/Shared/UI/Controller/
        namespace: App\Shared\UI\Controller
    type: attribute
