api_login_check:
    path: /api/login_check

api_logout:
    path: /api/logout

shared:
    resource:
        path: ../src/Shared/UI/Controller/
        namespace: App\Shared\UI\Controller
    type: attribute

user:
    resource:
        path: ../src/User/UI/Controller/
        namespace: App\User\UI\Controller
    type: attribute
